meta_product_name: "Max Hervé Composer"
meta_title: "Music Composer "
meta_description: "
Max Hervé is a music composer for visual media.
He started his career in 2013 in Los Angeles, becoming the assistant of Mychael Danna.
He has composed the music for many documentaries, TV shows, and worked on video games"
meta_image: "logo.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
