meta_title: "Maxime Hervé - Music Composer"
meta_description: "
Maxime Hervé is a music composer with a passion for orchestral music, electro and ethnic sounds.
He skillfully combines music and image on movies, series and games, for which he has been awarded at numerous festivals."
meta_image: "maxime_herve_contact.jpg" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards
